name: Deploy to GitHub Pages

on: 
  push:
    runs-on: [main]

jobs:
  deploy-to-pages:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      shell: bash
      run: |
        pip install --upgrade pip
        pip install -r docs/requirements.txt

    - name: Build HTML
      run: |
        cd docs
        make html
        sphinx-build -D language=en -b html ./ bulid/html

    - name: clean up files
      run: rm -r docs/_build/doctrees/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/html